# Generated by Django 4.0.3 on 2022-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_management', '0002_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(null=True, upload_to='shop_images'),
        ),
    ]
