# Generated by Django 4.0.3 on 2022-05-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_management', '0003_seller_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
