# Generated by Django 4.0.3 on 2022-05-19 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller_management', '0003_alter_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
