# Generated by Django 4.0.3 on 2022-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
